spring:
  application:
    name: estoque

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://estoque-db:5432/estoque
    username: user_estoque
    password: password_estoque

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql

server:
  port: 8089
