spring:
  application:
    name: estoque
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/estoque
    username: postgres
    password: docker
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql

server:
  port: 8089

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

spring.security.oauth2.resourceserver.jwt.issuer-uri: http://localhost:8080/realms/residencia

---
spring.config.activate.on-profile: docker
server.port: 8080
spring.datasource.url: jdbc:postgresql://172.17.0.1:5432/estoque
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
