spring.application.name: estoque
server.port: 8083

spring.datasource.driver-class-name: org.postgresql.Driver
spring.datasource.url: jdbc:postgresql://127.0.0.1:5433/estoque
spring.datasource.username: docker
spring.datasource.password: docker

spring.jpa.database: postgresql
spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: update

eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka
eureka.client.initialInstanceInfoReplicationIntervalSeconds: 5
eureka.client.registryFetchIntervalSeconds: 5
eureka.instance.leaseRenewalIntervalInSeconds: 5
eureka.instance.leaseExpirationDurationInSeconds: 5

management:
  server:
    port: 9093
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus

app:
  review-service:
    host: http://localhost:8082

# Docker profile

---
spring.config.activate.on-profile: docker

server.port: 8080
spring.datasource.url: jdbc:postgresql://database:5432/estoque
eureka.client.serviceUrl.defaultZone: http://discovery:8761/eureka/
spring.datasource.username: docker
spring.datasource.password: docker
app.catalogo-service.host: http://catalogo

management:
  server:
    port: 9000