services:
  database:
    build: database
    expose:
      - "5432"
    ports:
      - "5432:5432"

  discovery:
    build: discovery
    mem_limit: 512m
    ports:
      - "8761:8761"
    expose:
      - "8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  gateway:
    build: gateway
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DV_ADDRESS=discovery
    depends_on:
      - discovery 

  catalogo:
    build: catalogo
    mem_limit: 512m
    environment:
      - DB=catalogo
      - DB_ADDRESS=database
      - DB_USER=docker
      - DB_PASSWORD=docker
      - DV_ADDRESS=discovery
      - DV_PORT=8761
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - database
    expose:
      - "8087"


  preco:
    build: preco
    mem_limit: 512m
    environment:
      - DB=preco
      - DB_ADDRESS=database
      - DB_USER=docker
      - DB_PASSWORD=docker
      - DV_ADDRESS=discovery
      - DV_PORT=8761
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - database
    expose:
      - "8088"

  estoque:
    build: estoque
    mem_limit: 512m
    environment:
      - DB=estoque
      - DB_ADDRESS=database
      - DB_USER=docker
      - DB_PASSWORD=docker
      - DV_ADDRESS=discovery
      - DV_PORT=8761
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - database
    expose:
      - "8089"

