services:
  database:
    build: database
    expose:
      - "5432"

  catalogo:
    build: catalogo
    mem_limit: 512m
    environment:
      - DB=catalogo
      - DB_ADDRESS=database
      - DB_USER=docker
      - DB_PASSWORD=docker
      - DV_ADDRESS=discovery
      - DV_PORT=8091
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - database
    ports:
      - "8087:8087"


  preco:
    build: preco
    mem_limit: 512m
    environment:
      - DB=preco
      - DB_ADDRESS=database
      - DB_USER=docker
      - DB_PASSWORD=docker
      - DV_ADDRESS=discovery
      - DV_PORT=8091
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - database
    ports:
      - "8088:8088"

  estoque:
    build: estoque
    mem_limit: 512m
    environment:
      - DB=estoque
      - DB_ADDRESS=database
      - DB_USER=docker
      - DB_PASSWORD=docker
      - DV_ADDRESS=discovery
      - DV_PORT=8091
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - database
    ports:
      - "8089:8089"

  discovery:
    build: discovery
    mem_limit: 512m
    expose:
      - "8091"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  gateway:
    build: gateway
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8091/ # Alterado aqui
    depends_on:
      - eureka-server
    networks:
      - topicosEspeciais