services:
  database:
    build: database
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - app-network

  discovery:
    build: discovery
    mem_limit: 512m
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - app-network
  gateway:
    build: gateway
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - app-network

  catalogo:
    build: catalogo
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - database
      - message
    networks:
      - app-network

  preco:
    build: preco
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - database
    networks:
      - app-network

  estoque:
    build: estoque
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - database
    networks:
      - app-network

  message:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.4
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_IMPORT=/opt/keycloak/realm-export.json
#      - KC_DB=postgres                        # Usar o PostgreSQL como banco de dados
#      - KC_DB_USERNAME=keycloak               # Usuário do banco de dados
#      - KC_DB_PASSWORD=keycloak_password      # Senha do banco de dados
#     - KC_DB_URL_HOST=postgres               # Nome do serviço PostgreSQL
#      - KC_DB_URL_DATABASE=keycloak           # Nome do banco de dados
#      - KC_DB_URL_PORT=5432                   # Porta do PostgreSQL
    volumes:
      - ./autenticacao/import:/opt/keycloak/data/import
    ports:
      - "8090:8080"
    command: ["start-dev", "--import-realm"]
    networks:
      - app-network
#    depends_on:
#      - postgres

#  postgres:
#    image: postgres:15
#    environment:
#      - POSTGRES_DB=keycloak                  # Nome do banco de dados
#      - POSTGRES_USER=keycloak                # Usuário do banco de dados
#      - POSTGRES_PASSWORD=keycloak_password   # Senha do banco de dados
#    volumes:
#      - ./postgres-data:/var/lib/postgresql/data # Persistir os dados do PostgreSQL no host
#    ports:
#      - "5433:5432"                           # Porta para acessar o PostgreSQL

  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-network

  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    environment:
      - GF_SMTP_ENABLED=true
      - GF_SMTP_SKIP_VERIFY=true
      - GF_SMTP_HOST=maildev:1025
      - GF_SMTP_FROM_ADDRESS=grafana@minikube.me
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    networks:
      - app-network

  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"

networks:
  app-network:
    driver: bridge
