spring:
  application:
    name: preco

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://preco-db:5432/preco
    username: user_preco
    password: password_preco

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql

server:
  port: 8088
