spring.application.name: preco
server.port: 8088

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/preco
    username: postgres
    password: docker
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql

