spring:
  application:
    name: preco
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://preco-db:5432/preco
    username: user_preco
    password: password_preco

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql

server:
  port: 8088

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

spring.security.oauth2.resourceserver.jwt.issuer-uri: http://localhost:8080/realms/residencia

---
spring.config.activate.on-profile: docker
server:
  port: 8088
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_ADDRESS}:5432/${DB}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
eureka:
  client:
    serviceUrl:
      defaultZone: http://${DV_ADDRESS}:${DV_PORT}}/eureka
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
