server.port: 8080
spring.application.name: gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE

spring.cloud.gateway.routes:
  - id: catalogo
    uri: lb://catalogo
    predicates:
      - Path=/catalogo/**

  - id: eureka-web-start
    uri: http://${app.eureka-server}:8761
    predicates:
      - Path=/eureka/web
    filters:
      - SetPath=/

  - id: eureka-web-other
    uri: http://${app.eureka-server}:8761
    predicates:
      - Path=/eureka/**

app.eureka-server: localhost
---
spring.config.activate.on-profile: docker
app.eureka-server: ${DV_ADDRESS}
eureka:
  client:
    serviceUrl:
      defaultZone: http://${DV_ADDRESS}:8761/eureka/
