CREATE DATABASE catalogo;
CREATE DATABASE preco;
CREATE DATABASE estoque;
GRANT ALL PRIVILEGES ON DATABASE catalogo TO docker;
GRANT ALL PRIVILEGES ON DATABASE preco TO docker;
GRANT ALL PRIVILEGES ON DATABASE estoque TO docker;