CREATE DATABASE catalogo;
CREATE DATABASE produto;
CREATE DATABASE estoque;
GRANT ALL PRIVILEGES ON DATABASE catalogo TO docker;
GRANT ALL PRIVILEGES ON DATABASE produto TO docker;
GRANT ALL PRIVILEGES ON DATABASE estoque TO docker;