spring:
  application:
    name: catalogo
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/catalogo
    username: docker
    password: docker
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

management:
  server:
    port: 9091
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus


# Docker profile

---
spring.config.activate.on-profile: docker
spring:
  datasource:
    url: jdbc:postgresql://database:5432/catalogo
    username: docker
    password: docker

management:
  server:
    port: 9000

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
