spring:
  application:
    name: catalogo
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://database:5432/catalogo
    username: docker
    password: docker

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql

server:
  port: 8087

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#    initialInstanceInfoReplicationIntervalSeconds: 5
#    registryFetchIntervalSeconds: 5
#  instance:
#    leaseRenewalIntervalInSeconds: 5
#    leaseExpirationDurationInSeconds: 5

#spring.security.oauth2.resourceserver.jwt.issuer-uri: http://localhost:8080/realms/residencia

#---
#spring.config.activate.on-profile: docker
#server.port: 8080
#spring.datasource.url: jdbc:postgresql://database:5432/catalogo
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://discovery:8761/eureka/
