spring.application.name: catalogo
server.port: 8087

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/catalogo
    username: postgres
    password: docker
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
