server.port: 8761

eureka.instance.hostname: localhost
eureka.client.registerWithEureka: false
eureka.client.fetchRegistry: false
eureka.client.serviceUrl.defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
eureka.server.waitTimeInMsWhenSyncEmpty: 0
eureka.server.response-cache-update-interval-ms: 5000

management:
  server:
    port: 9100
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus

# Docker profile

---
spring.config.activate.on-profile: docker
management:
  server:
    port: 9000
